---
title: "Elaborazioni Gambero2025"
author: "Gianandrea LP"
date: 2025-06-25
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
	# -------------------------------------
	# dir.create('input', showWarnings = FALSE)
	# dir.create('output', showWarnings = FALSE)
	# dir.create('plots', showWarnings = FALSE)
	# dir.create('R-script', showWarnings = FALSE)
	library(pacman)
	p_load(tidyverse,stargazer,skimr,janitor,lubridate,
     	ggpubr,rstatix,openxlsx, patchwork, knitr, zoo)
	
	options(scipen = 9999)
	theme_set(theme_minimal(base_size = 18))
	# -------------------------------------
```

## Gambero 2025

Serie storica triennale su *Procambarus clarkii* del lago Trasimeno. Anni di riferimento: luglio 2018 - maggio 2021

```{r}
# import data
pc <- read.xlsx('input/Gamberi morfometria 3 anni_.xlsx',
                detectDates = T)
glimpse(pc)
```

## Controllo qualità dei dati

```{r}
pc %>% 
  select(where(is.numeric),sesso,-n) %>% 
  group_by(sesso) %>% 
  get_summary_stats(type = 'five_number') %>% 
  kable(digits = 2)
```

```{r fig.height=9, fig.width=13}
#| warning: false
pc %>% 
  select(where(is.numeric),sesso) %>% 
  pivot_longer(lt.carapace:peso.gonadi, 
               names_to = 'var', values_to = 'value') %>% 
  ggplot(aes(var,value))+
  geom_jitter(aes(col=sesso),alpha=0.5, size=2)+
  scale_y_sqrt()+
  facet_grid(~sesso)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0, hjust=1))+
  labs(x='')
```

```{r fig.height=9, fig.width=13}
#| warning: false
pc %>% 
  select(where(is.numeric),sesso) %>% 
  pivot_longer(lt.carapace:peso.gonadi, 
               names_to = 'var', values_to = 'value') %>% 
  filter(value<800) %>% 
  ggplot(aes(var,value))+
  geom_jitter(aes(col=sesso),alpha=0.2, size=2)+
  scale_y_sqrt()+
  facet_grid(~sesso)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0, hjust=1))+
  labs(x='')
```

```{r}
# add month and year
pc <- pc %>% 
  mutate(month=month(data),
         year=year(data),
         date=floor_date(data, unit = 'month'))
```

## Sex ratio

```{r sex}
clark.sex <- pc %>% 
  group_by(date,sesso) %>% 
  summarise(n=n()) %>% 
  mutate(tot=cumsum(n))
clark.sexratioF <- clark.sex %>% 
  filter(sesso=='F')
clark.sexratioM <- clark.sex %>% 
  filter(sesso=='M')
sexratio <- cbind(data.frame(ratio=round(clark.sexratioM$n/clark.sexratioF$n,1)),
                  distinct(pc,date))
```

```{r sex ratio, fig.height=9, fig.width=13}
pc %>% 
  count(sesso,date) %>% 
  group_by(date) %>% 
  mutate(perc=n/sum(n)) %>% 
  ggplot(aes(date,perc,group = sesso))+
  geom_bar(stat = 'identity', alpha=0.9, aes(fill=sesso))+
  scale_y_continuous(labels = scales::percent_format())+
  labs(x='',y='')+
  geom_label(data=sexratio, 
             aes(x=date,y=1.1,
             label=paste0(ratio,':1')),
             inherit.aes = FALSE,
             angle=90)+
  theme(legend.position = 'none')
```

## Mute

```{r mute, fig.height=9, fig.width=13}
mute <- pc %>% 
  filter(muta=='SI') %>% 
  count(sesso,date) %>% 
  mutate(perc=n/sum(n))
  
mute %>%
  mutate(perc=round(perc*100,2)) %>% 
  pivot_wider(id_cols=-n,names_from = sesso,values_from = perc) %>% 
  kable()
  
mute %>% ggplot(aes(date,perc,group = sesso))+
  geom_bar(stat = 'identity', alpha=0.9, aes(fill=sesso))+
  scale_y_continuous(labels = scales::percent_format())+
  labs(x='',y='')+
  theme(legend.position = 'none')
```

## Gonadi

```{r gonadi, fig.height=8, fig.width=11}
unique(pc$maturità.gonadi)
# corregge i nomi
pc$maturità.gonadi <- as.factor(pc$maturità.gonadi)
levels(pc$maturità.gonadi)[8] <- 'MATURE'

# crea una nuova variabile con stadio gonadi: 0, 1
pc.f <- pc %>% 
  filter(sesso=='F') %>% 
  mutate(gonadBin=ifelse(maturità.gonadi=='MATURE','1','0'))

pc.f %>% 
  count(date,gonadBin) %>% 
  ggplot(aes(x=date,y=n, group=gonadBin,col=gonadBin)) +
  geom_line(alpha=0.9, lwd=1.5) +
  geom_point(size=2) +
  ggtitle('Gonads') + ylab('numbers')+ xlab('')+
  scale_color_manual(values = c('#f78ae0','#f71ae8'))+
  theme(legend.position = 'none')
```

```{r gonadi2}
pc.f %>% 
  count(date,gonadBin) %>% 
  group_by(date) %>% 
  mutate(perc=round(n/sum(n)*100,2)) %>% 
  pivot_wider(id_cols = date, 
              values_from = perc, 
              names_from = gonadBin) %>% 
  kable()
```

```{r pgonadi, fig.height=9, fig.width=13}
pc.f %>% 
  count(date,gonadBin) %>% 
  group_by(date) %>% 
  mutate(perc=n/sum(n)) %>% 
  ggplot(aes(date,perc,group = gonadBin, fill=gonadBin))+
  geom_bar(stat = 'identity', alpha=0.9)+
  scale_y_continuous(labels = scales::percent_format())+
  labs(x='',y='')+
  scale_fill_manual(values = c('#f78ae0','#f71ae8'))+
  theme(legend.position = 'none')
```

## Attività maschi

```{r}

```

