---
output:
  html_document:
    css: css/bujo01.css
  pdf_document: default
---

# Progetto Gambero 2025

Serie storica triennale su *Procambarus clarkii* del lago Trasimeno. Anni di riferimento: luglio 2018 - maggio 2021

## Output elaborazioni

-   [file 3y con codice R](https://bioglp.github.io/gambero2025/R-script/000.gambero2025.html)
-   [file 20y con codice R](https://bioglp.github.io/gambero2025/R-script/000.gambero2025_20y.html)
-   file PDF

## Daily log
-   **2025-10-07**
    -   revisione delle date con trasformazione di:
        2000:2001 in :2011:2012
        2007:2009 in 2014:2016
        2018:2021 ok
-   **2025-08-26**
    -   trasformato in NA tutti i valori pari a 0
    -   inviato nuovo report
-   **2025-08-06**
    -   Barbara: corretti dati biometrici (file online condiviso)
    -   nuovo run script
-   **2025-07-31** 
    -   serie livelli idrometrici completa
    -   dati biometrici corretti (ancora qualcosa da correggere)
-   **2025-07-28**
    -   nuovo file 2000 - 2021, con campi rinominati e biometrie corrette
    -   elaborazione senza livelli idrometrici
-   **2025-07-23**
    -   invio nuovo file con campi rinominati da BARBARA
-   **2025-07-09** 
    -   necessario rivedere nome campi e uniformarli con il file precedente
    -   condivisione nuovo file 
-   **2025-07-07**
    -   [x] condivisione risultati secondo round
    -   invio nuovo file corretto xlsx
-   **2025-07-01**
    -   [x] condivisione risultati primo round
    -   completare riscrittura codice
    -   scaricare file idrometro da SIR Umbria
-   **2025-06-30**
    -   invio file corretto xlsx
-   **2025-06-29**
    -   richiesta revisione file dati
-   **2025-06-28**
    -   ~~riscrittura codici R (parziale)~~
-   **2025-06-26**
    -   invio file corretti (? lt.carapace)
-   **2025–06–25**
    -   invio dati Barbara (rivedere formato date)
    -   ~~recupero codici paper Biology 2021~~
    -   **incontro online su MSTeams**
        -   banca dati gambero 3 anni
        -   cfr. elaborazione Biology 2021
        -   download file SIR (idrometro)
