---
title: "Elaborazioni Gambero2025"
author: "Gianandrea LP"
date: 2025-07-07
format: html
theme: journal
editor: visual
subtitle: "[journal](https://bioglp.github.io/gambero2025)"
editor_options:
  chunk_output_type: console
---

```{r set, echo=FALSE}
# -------------------------------------
# dir.create('input', showWarnings = FALSE)
# dir.create('output', showWarnings = FALSE)
# dir.create('plots', showWarnings = FALSE)
# dir.create('R-script', showWarnings = FALSE)
library(pacman)
p_load(tidyverse,stargazer,skimr,janitor,lubridate, here, gt, 
       ggpubr,rstatix,openxlsx, patchwork, knitr, zoo)

options(scipen = 9999)
theme_set(theme_minimal(base_size = 18))
# -------------------------------------

# Imposta la palette globale
my_palette <- c("#f71ae8", "#33C6CA")

options(
    ggplot2.discrete.colour = my_palette,
    ggplot2.discrete.fill = my_palette
)
```

## Gambero 2025

Serie storica triennale su *Procambarus clarkii* del lago Trasimeno. Anni di riferimento: luglio 2018 - maggio 2021

```{r import data}
# import data
pc <- read.xlsx(here("input/Gamberi morfometria 3 anni_.xlsx"),
                detectDates = T)
# pc <- read.xlsx(here("input/Gamberi morfometria 2000-2021.xlsx"),
#                 detectDates = T)

glimpse(pc)
```

## Statistiche descrittive

```{r gt table}
pc %>% 
    select(where(is.numeric),sesso,-n) %>% 
    group_by(sesso) %>% 
    get_summary_stats(type = 'common') %>% 
    gt()
```

```{r fig.height=9, fig.width=13}
#| warning: false
pc %>% 
    select(where(is.numeric),sesso) %>% 
    pivot_longer(lt.carapace:peso.gonadi, 
                 names_to = 'var', values_to = 'value') %>% 
    filter(value<800) %>% # <- per eliminare outliers
    ggplot(aes(var,value))+
    geom_jitter(aes(col=sesso),alpha=0.2, size=2)+
    scale_y_sqrt()+
    
    stat_summary(
        aes(group = sesso),
        fun = mean,
        geom = "point",
        shape = 18, size = 3, col='black', alpha=0.5,
        position = position_dodge(width = 0.3) # per separare se necessario
    ) +
    
    labs(x='')+
    facet_grid(~sesso)+
    theme(legend.position = 'none',
          axis.text.x = element_text(angle = 90, vjust = 0, hjust=1))
```

```{r}
# add month and year
pc <- pc %>% 
    mutate(month=month(data),
           year=year(data),
           date=floor_date(data, unit = 'month'))
```

## Sex ratio

```{r sex}
sexratio <- pc %>% 
  count(date,sesso) %>% 
  pivot_wider(names_from = sesso,
              values_from = n) %>% 
  mutate(ratio=round(M/F,1))
```

```{r sex ratio, fig.height=9, fig.width=13}
pc %>% 
    count(sesso,date) %>% 
    group_by(date) %>% 
    mutate(perc=n/sum(n)) %>% 
    ggplot(aes(date,perc,group = sesso))+
    geom_bar(stat = 'identity', alpha=0.7, aes(fill=sesso))+
    scale_y_continuous(labels = scales::percent_format())+
    labs(x='',y='')+
    geom_label(data=sexratio, 
               aes(x=date,y=1.1,
                   label=paste0(ratio,':1')),
               inherit.aes = FALSE,
               angle=90)+
    theme(legend.position = 'none')
```

## Mute

```{r mute, fig.height=9, fig.width=13}
mute <- pc %>% 
    filter(muta=='SI') %>% 
    count(sesso,date) %>% 
    mutate(perc=n/sum(n))

mute %>%
    mutate(perc=round(perc*100,2)) %>% 
    pivot_wider(id_cols=-n,names_from = sesso,values_from = perc) %>% 
    kable()

mute %>% ggplot(aes(date,perc,group = sesso))+
    geom_bar(stat = 'identity', alpha=0.7, aes(fill=sesso))+
    scale_y_continuous(labels = scales::percent_format())+
    labs(x='',y='')+
    theme(legend.position = 'none')
```

## Gonadi

```{r gonadi, fig.height=8, fig.width=11}
# corregge i nomi
pc <- pc %>% mutate(maturità.gonadi=str_trim(maturità.gonadi))

# crea una nuova variabile con stadio gonadi: 0, 1
pc.f <- pc %>% 
    filter(sesso=='F') %>% 
    mutate(gonadBin=ifelse(maturità.gonadi=='MATURE','1','0'))

pc.f %>% 
    count(date,gonadBin) %>% 
    ggplot(aes(x=date,y=n, col=gonadBin)) +
    geom_line(alpha=0.9, lwd=1.5) +
    geom_point(size=4) +
    ggtitle('Gonads') + ylab('numbers')+ xlab('')+
    scale_color_manual(values = c('#f78ae0','#f71ae8'))+
    theme(legend.position = 'none')
```

```{r gonadi2}
pc.f %>% 
    count(date,gonadBin) %>% 
    group_by(date) %>% 
    mutate(perc=round(n/sum(n)*100,2)) %>% 
    pivot_wider(id_cols = date, 
                values_from = perc, 
                names_from = gonadBin) %>% 
    kable()
```

```{r pgonadi, fig.height=9, fig.width=13}
pc.f %>% 
    count(date,gonadBin) %>% 
    group_by(date) %>% 
    mutate(perc=n/sum(n)) %>% 
    ggplot(aes(date,perc,group = gonadBin, fill=gonadBin))+
    geom_bar(stat = 'identity', alpha=0.9)+
    scale_y_continuous('',labels = scales::percent_format())+
    scale_fill_manual('',labels=c('Immature','Mature'),
                      values = c('#f78ae0','#f71ae8'))+
    labs(x='',y='')+
    theme(legend.position = 'top')
```

## Attività maschi

```{r}
unique(pc$SA) #!malefici spazi!!!!
pc <- pc %>% mutate(SA=str_trim(SA))

pc.m <- pc %>% 
    filter(sesso=='M', !is.na(SA)) %>% 
    group_by(date,SA) %>% 
    count(date,SA) %>% 
    group_by(date) %>% 
    mutate(perc=n/sum(n))

pc.m %>% 
    pivot_wider(id_cols = date, 
                values_from = perc, 
                names_from = SA) %>% 
    kable(digits = 2)
```

```{r}
library(ggbreak) 
pc.m %>% 
    ggplot(aes(date,perc, fill=SA))+
    geom_col()+
    scale_fill_manual('',labels=c('Immature','Mature'), 
                      values=c("#A6E6E7","#33C6CA"))+
    scale_y_continuous('',labels = scales::percent_format())+
    labs(x='',y='')+
    theme(legend.position = 'top')
```

## Tw/B e Hiw

```{r}
# glimpse(pc)
pc.twb <- pc %>% 
    group_by(date,sesso) %>% 
    summarise(TwB=mean(TwB,na.rm=T), .groups = 'drop')
```

```{r fig.height=9, fig.width=13}
pc.twb %>% 
    ggplot(aes(date, TwB, col=sesso))+
    geom_point(size=4) +
    geom_line(alpha=0.9, lwd=1.3) +
    labs(y='Tw/B (mean value)', x='', tag = 'A')+
    theme(legend.position = 'none')
```

```{r}
pc.hiw <- pc %>% 
    group_by(date,sesso) %>% 
    summarise(Hiw=mean(Hiw,na.rm=T), .groups = 'drop')
```

```{r fig.height=9, fig.width=13}
pc.hiw %>% 
    ggplot(aes(date, Hiw, col=sesso))+
    geom_point(size=4) +
    geom_line(alpha=0.9, lwd=1.3) +
    labs(y='Hiw (mean value)', x='', tag = 'B')+
    theme(legend.position = 'none')
```

```{r fig.height=9, fig.width=13}
pc %>% 
  filter(year>=2019) %>% 
  ggplot(aes(sesso,Hiw))+
  geom_boxplot(aes(fill=sesso))+
  stat_compare_means(method = 't.test')+
  stat_summary(geom = "errorbar", 
                         fun.min = mean, fun = mean, fun.max = mean, 
                         width = .75, linetype='dashed')+
  labs(x='')+
  theme(legend.position = 'none')
```

```{r}
pc2019 <- pc %>% 
  filter(year>=2019)
t.test(Hiw~sesso, data=pc2019, var.equal=T)
```

```{r fig.height=9, fig.width=13}
pc %>% 
  filter(year>=2019) %>% 
  ggplot(aes(sesso,TwB))+
  geom_boxplot(aes(fill=sesso))+
  stat_compare_means(method = 't.test')+
  stat_summary(geom = "errorbar", 
                         fun.min = mean, fun = mean, fun.max = mean, 
                         width = .75, linetype='dashed')+
    labs(x='')+
  theme(legend.position = 'none')
```

```{r}
t.test(TwB~sesso, data=pc2019, var.equal=T)
```

## GSI

```{r}
pc.ind <- pc %>% 
    filter(sesso=='F') %>% 
    mutate(GSI=peso.gonadi/(peso.tot-peso.gonadi)*100) %>% 
    group_by(date) %>% 
    summarise(GSI=mean(GSI, na.rm = T),
              HIw=mean(Hiw, na.rm = T))
```

```{r fig.height=9, fig.width=13}
pc.ind %>% 
    ggplot(aes(date,GSI))+
    geom_point(col='brown',size=4)+
    geom_line(col='brown',lwd=1.3)+
    geom_point(aes(date,HIw/2),col='#F98178',size=4)+
    geom_line(aes(date,HIw/2),col='#F98178',lwd=1.3)+
    scale_y_continuous(sec.axis = sec_axis(~. /2, name = "HIw")) +
    labs(x='', tag = 'D') +
    theme(
        axis.title.y.left = element_text(color = "brown"),
        axis.title.y.right = element_text(color = "#F98178")
    )

pc.ind %>% 
    ggplot(aes(GSI,HIw))+
    geom_smooth(method = 'lm')+
    geom_point(size=3)+
    #stat_regline_equation()+
    stat_cor()
```

## Confronto con livelli idrometrici

```{r}
livello <- read.table(here('input/idrometro/idrometroSSavino.txt'),
                      header = T) 
liv <- livello %>% 
    pivot_longer(cols = X01:X12, values_to = 'avg', names_to = 'month')
liv$month <- rep(1:12,4)
liv <- liv %>%
    mutate(date=as_date(paste(year,month,'01',sep='-')))

liv %>% 
    ggplot(aes(date,avg))+
    geom_point()+
    geom_line()+
    labs(x='')
```

### mute

```{r fig.height=9, fig.width=13}
# head(mute)

mute %>% 
    ggplot(aes(date,n))+
    #geom_point(data=liv,aes(date,(avg+1)*100), col='#0082FF')+
    geom_line(data=liv,aes(date,(avg+1)*100), 
              col='#0082FF', alpha=0.2, lwd=3)+
    geom_point(aes(col=sesso), size=4)+
    geom_line(aes(col=sesso), lwd=1.3)+
    scale_y_continuous(sec.axis = sec_axis(~. /100-1, 
                                           name = "Hydrometric level")) +
    labs(x='', y='n') +
    theme(
        legend.position = 'none',
        axis.title.y.right = element_text(color = '#0082FF')
    )
```

```{r fig.height=9, fig.width=13}
library(rstatix)
library(ggpubr)

head(mute)
mute <- left_join(mute,liv,by = 'date') %>% as_tibble()
mute %>% 
  ggplot(aes(avg,perc, group=sesso, colour = sesso))+
  geom_smooth(method = 'lm')+
  geom_point()+
  facet_grid(~sesso)+
  stat_cor()
```

```{r}
mute %>% 
  group_by(sesso) %>% 
  cor_test(avg,perc)
```

```{r serieStorica}
library(tsibble)
library(feasts)
library(lubridate)

muteF <- mute %>% 
  filter(sesso=='F') %>% 
  dplyr::select(date,n,avg) %>% 
  as_tsibble(index=date)
  
monthly_muteF <- muteF |>
  mutate(date = yearmonth(date)) |>      # converte la data in formato mensile
  index_by(date) |>                      # imposta l’indice temporale mensile
  summarise(
    n = mean(n, na.rm = TRUE),
    avg = mean(avg, na.rm = TRUE)
  ) |> 
  fill_gaps()

autoplot(monthly_muteF, n) + labs(x='')
autoplot(monthly_muteF, avg) + labs(x='')

monthly_muteF %>% 
  ACF(n) %>% 
  autoplot()

monthly_muteF %>% 
  ACF(avg) %>% 
  autoplot()

monthly_muteF %>% 
  CCF(avg,n, type = 'correlation') %>% 
  autoplot()


library(vars)
data <- as.data.frame(muteF)
mod_var <- VAR(data[,-1], p = 2)
causality(mod_var, cause = "avg")
```

### Femmine mature

```{r fig.height=9, fig.width=13}
# head(pc.f)

pc.f %>% 
    filter(maturità.gonadi=='MATURE') %>% 
    count(date,maturità.gonadi) %>% 
    ggplot(aes(date,n))+
    geom_line(data=liv,aes(date,(avg+1)*100), 
              col='#0082FF', alpha=0.2, lwd=3)+
    geom_point(col='#F19837', size=4)+
    geom_line(col='#F19837', lwd=1.3)+
    labs(x='', y='n')
```

```{r fig.height=9, fig.width=13}
pc.f %>% 
  filter(maturità.gonadi=='MATURE',
         year>=2019) %>% 
  count(date,maturità.gonadi) %>% 
  left_join(liv,by='date') %>% 
  ggplot(aes(avg,n))+
  geom_smooth(method = 'lm')+
  geom_point(col='#F19837', size=4)+
  stat_cor()
```

```{r}
pc.f %>% 
  filter(maturità.gonadi=='MATURE',
         year>=2019) %>% 
  count(date,maturità.gonadi) %>% 
  left_join(liv,by='date') %>% 
  cor_test(n,avg)
```

# Chimica

```{r datiChimici}
chimLudo <- read.xlsx(here('input/chimLudoEn.xlsx'))
chimLudo <- as_tibble(chimLudo)
glimpse(chimLudo)
chimLudo$date <- as.Date(str_c(chimLudo$year+2000,'-',chimLudo$month,'-01'))

clarkChim <- left_join(pc,chimLudo, by='date')
glimpse(clarkChim)
```

# PCA

```{r PCA}
library(factoextra)
library(lubridate)

df <- readRDS('input/clarkChim.RDS')
metalli <- read.xlsx('input/metalliMean.xlsx',detectDates = T)

df <- left_join(df,metalli)

# 1. Crea la variabile stagione
df.pca <- df %>%
  dplyr::select(date, sesso, SODM:MTH,
                Secchi, `T-avg`, `pH-avg`, 
                `DO-avg`, `cond-avg`, 
                `Hydrometric level`, Cr.M:Fe.H) %>%
  na.omit()

df.pca$date <- as.Date(df.pca$date)

# Funzione per assegnare la stagione
get_season <- function(dates) {
  m <- month(dates)
  ifelse(m %in% c(12, 1, 2), "Winter",
  ifelse(m %in% c(3, 4, 5), "Spring",
  ifelse(m %in% c(6, 7, 8), "Summer", "Autumn")))
}

df.pca$Stagione <- factor(get_season(df.pca$date),
                          levels = c("Winter", 
                                     "Spring", 
                                     "Summer", 
                                     "Autumn"))
# 2. prcomp
df.pca.num <- df.pca %>%
  filter(sesso=='M') %>% 
  dplyr::select(where(is.numeric))

pca_res <- prcomp(df.pca.num, scale. = TRUE)

# 3. MALES
fviz_pca_biplot(pca_res,
             geom.ind = "point",
             col.ind = df.pca$Stagione[df.pca$sesso=='M'],
             palette = "Set2",
             addEllipses = TRUE,
             legend.title = "Season") +
  ggtitle("PCA - Seasonal differences in males") +
  theme_minimal()
ggsave('plots/pcaMalesMetalli.pdf', width = 9, height = 7)

# 2. prcomp
df.pca.num <- df.pca %>%
  filter(sesso=='F') %>% 
  dplyr::select(where(is.numeric))

pca_res <- prcomp(df.pca.num, scale. = TRUE)

# 3. FEMALES
fviz_pca_biplot(pca_res,
             geom.ind = "point",
             col.ind = df.pca$Stagione[df.pca$sesso=='F'],
             palette = "Set2",
             addEllipses = TRUE,
             legend.title = "Season") +
  ggtitle("PCA - Seasonal differences in females") +
  theme_minimal()
ggsave('plots/pcaFemalesMetalli.pdf', width = 9, height = 7)
```

```{r metalliEnzimi}
library(rstatix)
GPxM <- df %>% 
  select(Cr.M,Hg.M,Cd.M,Pb.M,Ag.M,Ni.M,MTM,GPxM) %>% 
  cor_test(Cr.M:Ni.M,GPxM) %>% 
  filter(var2=='GPxM', var1!='GPxM')

MTM <- df %>% 
  select(Cr.M,Hg.M,Cd.M,Pb.M,Ag.M,Ni.M,MTM,GPxM) %>% 
  cor_test(Cr.M:Ni.M,MTM) %>% 
  filter(var2=='MTM', var1!='MTM')

GPxH <- df %>% 
  select(Cr.H,Hg.H,Cd.H,Pb.H,Ag.H,Ni.H,MTH,GPxH) %>% 
  cor_test(Cr.H:Ni.H,GPxH) %>%
  filter(var2=='GPxH', var1!='GPxH')

MTH <- df %>% 
  select(Cr.H,Hg.H,Cd.H,Pb.H,Ag.H,Ni.H,MTH,GPxH) %>% 
  cor_test(Cr.H:Ni.H,MTH) %>%
  filter(var2=='MTH', var1!='MTH')

corr <- rbind(GPxM,GPxH,MTM,MTH)
corr %>% 
  write.xlsx('correlazioni20251105.xlsx')

corr %>% 
  ggplot(aes(var2,var1))+
  geom_point(aes(col=cor>0, size=cor))+
  scale_size(range = c(5,20))+
  geom_text(aes(label=cor),size=3)+
  labs(x='',y='')+
  theme(legend.position = 'none')
ggsave('correlazioni20251105.pdf',height = 9, width = 5)  
```